import type { HabitCategory } from "@/types";

export const defaultHabits: HabitCategory[] = [
  { id: "alcool", label: "Alcool", description: "Verres en semaine ou soirées alcoolisées.", category: "Boissons", defaultImpactCalories: 5, examples: ["bière", "vin", "cocktails"], suggestedAlternatives: ["maximum 1 soirée alcool par semaine", "alterner avec eau pétillante"], warningText: "Si l’alcool est difficile à réduire seul, demande un accompagnement adapté." },
  { id: "boissons-sucrees", label: "Boissons sucrées", description: "Sodas, jus, boissons énergétiques ou cafés sucrés.", category: "Boissons", defaultImpactCalories: 4, examples: ["soda au déjeuner", "jus le matin"], suggestedAlternatives: ["version sans sucre", "eau aromatisée maison"] },
  { id: "grignotage-sucre", label: "Grignotage sucré", description: "Biscuits, chocolat, desserts hors repas.", category: "Grignotage", defaultImpactCalories: 4, examples: ["biscuits au travail", "chocolat le soir"], suggestedAlternatives: ["portion prévue", "fruit + yaourt grec"] },
  { id: "grignotage-sale", label: "Grignotage salé", description: "Chips, crackers, apéritifs salés.", category: "Grignotage", defaultImpactCalories: 4, examples: ["apéritif", "chips devant écran"], suggestedAlternatives: ["crudités + sauce légère", "portion dans un bol"] },
  { id: "fromage", label: "Fromage", description: "Fromages denses fréquents ou portions qui montent vite.", category: "Densité calorique", defaultImpactCalories: 4, examples: ["comté", "raclette", "plateau fromage"], suggestedAlternatives: ["fromage plaisir 2 fois/semaine", "fromage frais léger"] },
  { id: "charcuterie", label: "Charcuterie", description: "Produits gras et salés en repas ou apéritif.", category: "Densité calorique", defaultImpactCalories: 4, examples: ["saucisson", "pâté", "jambon cru"], suggestedAlternatives: ["jambon blanc", "oeufs", "volaille"] },
  { id: "pain-viennoiseries", label: "Pain, viennoiseries, pâtisseries", description: "Pain en grande quantité, croissants, gâteaux.", category: "Glucides denses", defaultImpactCalories: 4, examples: ["pain à chaque repas", "croissant", "pâtisserie"], suggestedAlternatives: ["portion mesurée", "pain complet", "dessert plaisir planifié"] },
  { id: "feculents-portions", label: "Féculents et portions", description: "Portions qui dépassent la faim réelle.", category: "Portions", defaultImpactCalories: 3, examples: ["pâtes resservies", "riz très généreux"], suggestedAlternatives: ["assiette 1/2 légumes", "portion unique puis pause"] },
  { id: "ultra-transformes", label: "Plats préparés et ultra-transformés", description: "Repas très pratiques mais souvent denses et peu rassasiants.", category: "Qualité alimentaire", defaultImpactCalories: 4, examples: ["pizza industrielle", "plats micro-ondes"], suggestedAlternatives: ["assemblage simple protéine + légumes", "batch cooking minimal"] },
  { id: "sauces-gras", label: "Sauces, huiles, beurre, crème", description: "Matières grasses ajoutées sans mesure.", category: "Densité calorique", defaultImpactCalories: 4, examples: ["huile à l’œil", "crème", "sauce mayo"], suggestedAlternatives: ["cuillère mesurée", "sauce yaourt", "épices"] },
  { id: "repas-soir", label: "Repas du soir", description: "Repas tardifs, très riches ou deuxième repas plaisir.", category: "Rythme", defaultImpactCalories: 4, examples: ["gros dîner", "fromage + dessert"], suggestedAlternatives: ["règle du dîner simple", "protéines + légumes + plaisir mesuré"] },
  { id: "weekend-social", label: "Repas sociaux et week-end", description: "Accumulation de repas plus riches en peu de temps.", category: "Contexte", defaultImpactCalories: 5, examples: ["restaurant", "apéritif", "repas famille"], suggestedAlternatives: ["1 repas très plaisir", "règle simple avant/après"] },
  { id: "legumes", label: "Manque de légumes", description: "Peu de volume alimentaire rassasiant.", category: "Rassasiement", defaultImpactCalories: 3, examples: ["assiette sans légumes", "sandwich seul"], suggestedAlternatives: ["légumes à chaque dîner", "soupe ou crudités faciles"] },
  { id: "proteines", label: "Manque de protéines rassasiantes", description: "Repas qui calent peu et déclenchent l’envie de grignoter.", category: "Rassasiement", defaultImpactCalories: 3, examples: ["petit déjeuner sucré", "salade légère"], suggestedAlternatives: ["protéine à chaque repas", "yaourt grec ou oeufs"] },
  { id: "sedentarite", label: "Sédentarité", description: "Temps assis élevé et peu de mouvement quotidien.", category: "Mouvement", defaultImpactCalories: 3, examples: ["journée bureau", "voiture"], suggestedAlternatives: ["10 minutes après repas", "appels en marchant"] },
  { id: "activite-physique", label: "Activité physique", description: "Peu d’activité régulière hors contraintes.", category: "Mouvement", defaultImpactCalories: 3, examples: ["sport irrégulier", "seulement foot"], suggestedAlternatives: ["2 marches/course facile", "mobilité / Circuit Vital"] },
  { id: "sommeil", label: "Sommeil", description: "Nuits courtes ou irrégulières qui augmentent faim et impulsivité.", category: "Récupération", defaultImpactCalories: 2, examples: ["coucher tard", "réveils nocturnes"], suggestedAlternatives: ["heure écran coupée", "routine 20 minutes"] },
  { id: "stress-emotion", label: "Stress et alimentation émotionnelle", description: "Manger pour amortir stress, fatigue ou tension.", category: "Émotion", defaultImpactCalories: 4, examples: ["snack après journée dure", "envie urgente"], suggestedAlternatives: ["pause 10 minutes", "marche courte", "snack cadré"] },
  { id: "faim-envie", label: "Faim réelle vs envie", description: "Difficulté à distinguer besoin du corps et envie de contexte.", category: "Pilotage", defaultImpactCalories: 3, examples: ["manger par automatisme", "finir le paquet"], suggestedAlternatives: ["question faim 0-10", "portion puis pause"] },
  { id: "repas-plaisir", label: "Repas plaisir ou craquage", description: "Repas plaisir qui deviennent une séquence non pilotée.", category: "Pilotage", defaultImpactCalories: 4, examples: ["un repas devient week-end complet", "commande impulsive"], suggestedAlternatives: ["plaisir prévu", "retour au repas simple suivant"] },
];
